name: Lint

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v4

      - name: Go fmt
        run: make lint

      - name: Go vet
        run: make vet
