name: Test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Golang
      uses: actions/setup-go@v4

    - name: Run tests
      run: make test
